title: Jake's Frontend Portfolio
email: hamiltonjacoba@gmail.com
description: >-
  Jake's Frontend Portfolio

# Build settings
markdown: kramdown
kramdown:
  input: GFM
sass:
  style: compressed
include: ['_pages']
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
